### PR TITLE
Added two new settings - showRightArrow and itemLimit

### PR DESCRIPTION
**Pull request by RichardDalton**
**showRightArrow** (defaulted to true to maintain current behaviour) to give the option to hide the right arrow icon in the generated list view.

**itemLimit** to restrict the number of items returned while searching.

### CODE REVIEW

**Comment by commadelimited** [comment]
Infernal badger...

Would you mind also adding a demo page showing these changes in action? It'll help me verify functionality before merge. Thanks for committing.

**Comment by RichardDalton** [comment]
Andy, I have added settings.html with examples for these two settings. 

Let me know if there are any problems with this.

**Comment by neilcoplin** [comment]
Would it just make more sense instead of using a "showRightArrow" option, to just allow the user to specify what the icon they want it to be?  For some applications of the widget, a right arrow may not make sense where some other icon could.  You could of course always specify the icon "none" to then achieve the same result.  Would be a bit more flexible, IMO.

**Comment by RichardDalton** [comment]
Yeah, you are right. I will make that change later and add it to this request. Thanks.

**Comment by commadelimited** [comment]
Good idea Neil.

**Comment by neilcoplin** [comment]
I had actually already done that on a local copy, so I've included it in a new pull request that also included the ajax call cancelling.

**Pull request closed without merging**
