### PR TITLE
Added convenience methods to update, clear and destroy plugin

### PR DESCRIPTION
**Pull request by jmpease**
- Added an "update" method that allows changing of autoComplete settings after the plugin has been initialized on an element.
- Added a "clear" method that empties the target listview.  Useful for clearing the list in response to non-"input" events.
- Added a "destroy" method to unbind event handler and clear stored plugin data.  Useful when plugin functionality is no-longer required.
- Added namespaced targetUpdated and targetCleared events.
- Calling unbind before bind in initializer to avoid redundant handling in case plugin is re-initialized on an element.
- Fixed clearing of target listview when input length is less than minLength, rather than 1.
- Added Eclipse project metadata for consistency amongst developers using Eclipse.

### CODE REVIEW

**Comment by jmpease** [comment]
Oops...bad timing it seems.  Missed the recent upstream update to 1.2.  I'll look into merging these into this request.

**Comment by commadelimited** [comment]
LOL. I just did it this morning. These additions sound awesome JM.

**Comment by jmpease** [comment]
I merged in the changes from the upstream 1.2 version into a new 1.3 version including my changes.  Take a look and let me know what you think.

Re formatting...I stuck with a local customization of the Eclipse JS formatter.  Let me know what convention(s) you prefer (e.g. tab policy, indent size, brace positions) and I can modify the settings appropriately.

**Comment by commadelimited** [comment]
Jim...

I'm going to be pushing these changes to the repo but I wasn't able to merge them in as I had already made some other changes. I'm going to make sure you're credited however.

**Pull request closed without merging**
