### PR TITLE
Accept function as a source.

### PR DESCRIPTION
**Pull request by spacenick**
Function needs to call the callback, which is the first parameter.
source:function(callback) { mydata = [1,2]; callback(mydata); }

### CODE REVIEW

**Comment by apeckham** [comment]
+1 awesome, I was just looking for this.

**Comment by apeckham** [comment]
Do you think the source function should also be passed the "text" var -- which contains the text the user typed? Seems important when deciding what suggestions to return. https://github.com/apeckham/autoComplete.js/commit/744bbc341c5944f7eb4c1af6939ef0d1709543ec#jqm.autoComplete-1.3.js

**Comment by spacenick** [comment]
Definately, yes!

**Comment by commadelimited** [comment]
Spacenick...

In addition to this change to the main library, can you please write a demo page?

Also, it might be a little while before I can merge this. I'm planning on rewriting the entire module using jQuery UI's Widget Factory. That'll make it much easier to add new functionality. Plus it'll give me a good foundation to use for writing unit tests.

**Comment by commadelimited** [comment]
Spacenick...

I've put the rewrite on hold so I'm planning on merging this in. Before I do so, I'd love for you to write up a quick demo page as well as update the readme on usage for this new functionality.

**Comment by samy80** [comment]
Was precisely looking for that feature, but had to search a little while to finaly find this thread. 

The Usage & Documentation section of the readme.md file could definitely be updated, as there's no trace there of this useful functionality.

**Comment by pwegrzy** [comment]
I was looking for exactly this same thing as well, as I am going to try to implement a call to a local websql table here with autocomplete filtering (the entire table is too big to preload it all into an array/object), glad I found this. agree that it would be great if the doc/demo showed this feature.

**Pull request merged**
